### ISSUE TITLE
Article on *.dev domains no longer valid.

### ISSUE THREAD

**Issue by ringods** [mhutter/hutter.io#16]
@mhutter I took a peek at your blog and noticed one of the articles is no longer (partially) valid:

https://hutter.io/2016/02/02/make-all-dev-domains-resolve-to-localhost/

Recent releases of Chrome and Firefox insist on *.dev domains to be hosted via https forced by HSTS preload. More details here:

https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

I think it's a good idea to add a big fat note/warning at the top of the article pointing to the above article. :-)

**Comment by mhutter** [comment]
Good catch! Maybe I can update the article to use a different TLD, have to verify this still works though :-)

**Comment by mhutter** [comment]
Fixed. Thank you for taking your time to report this, @ringods 🍻

**Comment by ringods** [comment]
No problem. BTW, good link to Troy Hunt's article! 👍
